Name:           perl-marc-moose
Version:        1.0.31
Release:        2%{?dist}
Summary:        marc::moose Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/marc-moose/
Source0:        http://www.cpan.org/authors/id/F/FR/FREDERICD/marc-moose-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.010
BuildRequires:  perl(AnyEvent::Processor)
BuildRequires:  perl(Carp)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Slurp)
BuildRequires:  perl(Getopt::Long)
BuildRequires:  perl(JSON)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(MARC::File::XML)
BuildRequires:  perl(MARC::Record)
BuildRequires:  perl(Modern::Perl)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(Moose::Util::TypeConstraints)
BuildRequires:  perl(MooseX::RW::Reader)
BuildRequires:  perl(MooseX::RW::Reader::File)
BuildRequires:  perl(MooseX::RW::Writer)
BuildRequires:  perl(Pod::Usage)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Text::Iconv) >= 1.7
BuildRequires:  perl(Time::HiRes)
BuildRequires:  perl(utf8)
BuildRequires:  perl(warnings)
BuildRequires:  perl(XML::SAX)
BuildRequires:  perl(XML::SAX::Base)
BuildRequires:  perl(XML::Simple)
BuildRequires:  perl(XML::Writer)
BuildRequires:  perl(YAML)
BuildRequires:  perl(YAML::Syck)
BuildRequires:  perl(File::ShareDir::Install)
Requires:       perl(AnyEvent::Processor)
Requires:       perl(Carp)
Requires:       perl(Getopt::Long)
Requires:       perl(JSON)
Requires:       perl(List::Util)
Requires:       perl(MARC::Record)
Requires:       perl(Modern::Perl)
Requires:       perl(Moose)
Requires:       perl(Moose::Role)
Requires:       perl(Moose::Util::TypeConstraints)
Requires:       perl(MooseX::RW::Reader)
Requires:       perl(MooseX::RW::Reader::File)
Requires:       perl(MooseX::RW::Writer)
Requires:       perl(Pod::Usage)
Requires:       perl(strict)
Requires:       perl(Text::Iconv) >= 1.7
Requires:       perl(utf8)
Requires:       perl(warnings)
Requires:       perl(XML::SAX)
Requires:       perl(XML::SAX::Base)
Requires:       perl(XML::Simple)
Requires:       perl(XML::Writer)
Requires:       perl(YAML)
Requires:       perl(YAML::Syck)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
marc::moose Perl module

%prep
%setup -q -n marc-moose-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE README weaver.ini
%{_bindir}/marcmoose
%{_bindir}/marcmoose-lint
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*

%changelog
* Thu May 26 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 1.0.31-1
- Update BuildRequires
* Thu May 26 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 1.0.31-1
- Specfile autogenerated by cpanspec 1.78.
