Name:		perl-PDF-API2-Simple
Version:	1.1.4
Release:	2%{?dist}
Summary:	Simplistic wrapper for the PDF::API2 modules

Group:		Development/Libraries
License:	Public Domain
URL:		http://search.cpan.org/dist/PDF-API2-Simple/
Source0:	http://search.cpan.org/CPAN/authors/id/R/RE/REDTREE/PDF-API2-Simple-1.1.4u.tar.gz
BuildRoot:	 %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:	noarch
BuildRequires:	perl-Module-Install
BuildRequires:	perl(Test::More)
BuildRequires:	perl(PDF::API2)
BuildRequires:	perl-JSON-PP
Requires:	perl(PDF::API2)
Requires:	perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Provides a wrapper to access PDF-API2 modules.

%prep
%setup -q -n PDF-API2-Simple-%{version}


%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}


%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT


%files
%defattr(-,root,root,-)
%doc README
%{perl_vendorlib}/*
%{_mandir}/man3/*



%changelog
* Thu Apr 28 2011 Nicholas van Oudtshoorn 1.1.4-1
- Specfile generated by hand
