Name:           perl-Module-Bundled-Files
Version:        0.03
Release:        1%{?dist}
Summary:        Access files bundled with Module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Module-Bundled-Files/
Source0:        http://www.cpan.org/authors/id/P/PC/PCAMPBELL/Module-Bundled-Files-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Class::ISA)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Module::Build) >= 0.26
BuildRequires:  perl(Test::More)
Requires:       perl(Class::ISA)
Requires:       perl(File::Spec)
Requires:       perl(Module::Build) >= 0.26
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides an simple method of accessing files that need to be
bundled with a module.

%prep
%setup -q -n Module-Bundled-Files-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 0.03-1
- Specfile autogenerated by cpanspec 1.78.
