Name:           perl-OpenOffice-OODoc
Version:        2.125
Release:        1%{?dist}
Summary:        Perl Open OpenDocument Connector
License:        LGPLv2+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/OpenOffice-OODoc/
Source0:        http://www.cpan.org/authors/id/J/JM/JMGDOC/OpenOffice-OODoc-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Archive::Zip) >= 1.18
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Temp) >= 0.12
BuildRequires:  perl(Time::Local) >= 1.07
BuildRequires:  perl(XML::Twig) >= 3.32
Requires:       perl(Archive::Zip) >= 1.18
Requires:       perl(File::Temp) >= 0.12
Requires:       perl(Time::Local) >= 1.07
Requires:       perl(XML::Twig) >= 3.32
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This toolbox is an extensible Perl interface allowing direct read/write
operations on files which comply with the OASIS Open Document Format for
Office Applications (ODF), i.e. the ISO/IEC 26300:2006 standard.

%prep
%setup -q -n OpenOffice-OODoc-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor --noprompt
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc build_date Changes LICENCE oodoc_version README
%{_bindir}/*
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*

%changelog
* Wed Aug 12 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 2.125-1
- Specfile autogenerated by cpanspec 1.78.
