Name:           perl-Text-Bidi
Version:        2.09
Release:        1%{?dist}
Summary:        Unicode bidi algorithm using libfribidi
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Text-Bidi/
Source0:        http://www.cpan.org/authors/id/K/KA/KAMENSKY/Text-Bidi-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl >= 1:v5.10.0
BuildRequires:  perl(Carp)
BuildRequires:  perl(Data::Dumper)
BuildRequires:  perl(Encode)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(File::Spec::Functions)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Getopt::Long)
BuildRequires:  perl(List::Util)
BuildRequires:  perl(open)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(version) >= 0.77
BuildRequires:  fribidi-devel
Requires:       perl(Carp)
Requires:       perl(Encode)
Requires:       perl(Exporter)
Requires:       perl(Getopt::Long)
Requires:       perl(open)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       fribidi-devel

%description
This module provides basic support for the Unicode bidirectional (Bidi)
text algorithm, for displaying text consisting of both left-to-right and
right-to-left written languages (such as Hebrew and Arabic.) It does so via
a swig interface file to the libfribidi library.

%prep
%setup -q -n Text-Bidi-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
TEXT_BIDI_SKIP_UCD=1 make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes cpanfile dist.ini LICENSE META.json weaver.ini
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Text*
%{_bindir}/fribidi.pl
%{_mandir}/man3/*
%{_mandir}/man1/*

%changelog
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 2.09-1
- Specfile autogenerated by cpanspec 1.78.
