Name:           perl-MooseX-Attribute-ENV
Version:        0.02
Release:        1%{?dist}
Summary:        Set default of an attribute to a value from %ENV
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MooseX-Attribute-ENV/
Source0:        http://www.cpan.org/authors/id/J/JJ/JJNAPIORK/MooseX-Attribute-ENV-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 1:5.8.6
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Moose) >= 0.48
BuildRequires:  perl(Test::More)
BuildRequires:  perl(CPAN)
Requires:       perl(Moose) >= 0.48
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is a Moose attribute trait that you use when you want the default
value for an attribute to be populated from the %ENV hash. So, for example
if you have set the environment variable USERNAME = 'John' you can do:

%prep
%setup -q -n MooseX-Attribute-ENV-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes MYMETA.json MYMETA.yml README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Sep 29 2015 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.02-1
- Specfile autogenerated by cpanspec 1.78.
