Name:           perl-Text-Unaccent
Version:        1.08
Release:        1%{?dist}
Summary:        Remove accents from a string
License:        GPLv2+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Text-Unaccent/
Source0:        http://www.cpan.org/authors/id/L/LD/LDACHARY/Text-Unaccent-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Text::Unaccent is a module that remove accents from a string. unac_string
converts the input string from the specified charset to UTF-16 and call
unac_string_utf16 to return the unaccented equivalent. The conversion from
and to UTF-16 is done with iconv(1).

%prep
%setup -q -n Text-Unaccent-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc ChangeLog COPYING README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Text*
%{_mandir}/man3/*

%changelog
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 1.08-1
- Specfile autogenerated by cpanspec 1.78.
