Name:           perl-Config-Onion
Version:        1.006
Release:        1.git.0.dd27289%{?dist}
Summary:        Layered configuration, because configs are like ogres
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Config-Onion/
Source0: perl-Config-Onion-git-0.dd27289.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Config::Any)
BuildRequires:  perl(Exporter)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Hash::Merge::Simple)
BuildRequires:  perl(Moo)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::Exception)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(warnings)
BuildRequires:  perl(YAML)
Requires:       perl(Config::Any)
Requires:       perl(Exporter)
Requires:       perl(Hash::Merge::Simple)
Requires:       perl(Moo)
Requires:       perl(strict)
Requires:       perl(warnings)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
All too often, configuration is not a universal or one-time thing, yet
most configuration-handling treats it as such. Perhaps you can only load
one config file. If you can load more than one, you often have to load
all of them at the same time or each is stored completely independently,
preventing one from being able to override another. Config::Onion
changes that.

%prep
%setup -q -n perl-Config-Onion-git-0.dd27289

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README.mkdn
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Jun 02 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 1.006-1
- Specfile autogenerated by cpanspec 1.78.
