Name:           perl-AnyEvent-Processor
Version:        0.006
Release:        2%{?dist}
Summary:        Base class to define an event-driven (AnyEvent) task that could periodically be interrupted by a watcher
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/AnyEvent-Processor/
Source0:        http://www.cpan.org/authors/id/F/FR/FREDERICD/AnyEvent-Processor-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(AnyEvent)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Glib)
BuildRequires:  perl(Modern::Perl)
BuildRequires:  perl(Moose)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(warnings)
Requires:       perl(AnyEvent)
Requires:       perl(Glib)
Requires:       perl(Modern::Perl)
Requires:       perl(Moose)
Requires:       perl(Moose::Role)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Provides:       perl(AnyEvent::Processor)
%description
A processor task based on this class process anything that can be divided
into processing clusters. Each cluster is processed one by one by calling
the process() method. A count is incremented at the end of each cluster. By
default, a AnyEvent::Processor::Watcher is associated with the class,
interrupting the processing each second for calling process_message.

%prep
%setup -q -n AnyEvent-Processor-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE README weaver.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Dec 13 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.006-2
- Manual provides
* Thu May 26 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.006-1
- Specfile autogenerated by cpanspec 1.78.
