Name:           perl-Net-Z3950-ZOOM
Version:        1.30
Release:        1%{?dist}
Summary:        Perl extension for invoking the ZOOM-C API
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Net-Z3950-ZOOM/
Source0:        http://www.cpan.org/authors/id/M/MI/MIRK/Net-Z3950-ZOOM-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(MARC::Record) >= 1.38
BuildRequires:  perl(Test::More)
BuildRequires:  libyaz-devel
Requires:       perl(MARC::Record) >= 1.38
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       libyaz
%description
This module provides a simple thin-layer through to the ZOOM-C functions in
the YAZ toolkit for Z39.50 and SRW/U communication. You should not be using
this very nasty, low-level API. You should be using the ZOOM module
instead, which implements a nice, Perlish API on top of this module,
conformant to the ZOOM Abstract API described at http://zoom.z3950.org/api/

%prep
%setup -q -n Net-Z3950-ZOOM-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{_bindir}/*
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Net*
%{perl_vendorarch}/ZOOM*

%{_mandir}/man3/*

%changelog
* Wed Aug 12 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 1.30-1
- Specfile autogenerated by cpanspec 1.78.
