Name:           perl-MARC-Crosswalk-DublinCore
Version:        0.02
Release:        1%{?dist}
Summary:        Convert data between MARC and Dublin Core
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MARC-Crosswalk-DublinCore/
Source0:        http://www.cpan.org/authors/id/B/BR/BRICAS/MARC-Crosswalk-DublinCore-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(DublinCore::Record)
BuildRequires:  perl(MARC::Record)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
Requires:       perl(DublinCore::Record)
Requires:       perl(MARC::Record)
Requires:       perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module provides an implentation of the LOC's spec on how to convert
metadata between MARC and Dublin Core format. The spec for converting MARC
to Dublin Core is available at: http://www.loc.gov/marc/marc2dc.html, and
from DC to MARC: http://www.loc.gov/marc/dccross.html.

%prep
%setup -q -n MARC-Crosswalk-DublinCore-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{_bindir}/marc2dc
%{perl_vendorlib}/*
%{_mandir}/man3/*
%{_mandir}/man1/*

%changelog
* Wed Aug 12 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 0.02-1
- Specfile autogenerated by cpanspec 1.78.
