Name:           perl-Crypt-GCrypt
Version:        1.26
Release:        2%{?dist}
Summary:        Crypt::GCrypt Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Crypt-GCrypt/
Source0:        http://www.cpan.org/authors/id/A/AA/AAR/Crypt-GCrypt-%{version}.tar.gz
Patch0:         Crypt-GCrypt.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test)
BuildRequires:  libgcrypt-devel
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Requires:       libgcrypt

%description
Crypt::GCrypt provides a Perl interface to the libgcrypt cryptographic
functions. It currently supports symmetric ciphers such as AES/Rikndael,
Twofish, Triple DES, Arcfour etc., while asymmetric cryptography is being
developed.

%prep
%setup -q -n Crypt-GCrypt-%{version}
%patch0 -p0

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor OPTIMIZE="$RPM_OPT_FLAGS"
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -type f -name '*.bs' -size 0 -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changelog META.json README
%{perl_vendorarch}/auto/*
%{perl_vendorarch}/Crypt*
%{_mandir}/man3/*

%changelog
* Tue Dec 13 2016 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 1.26-2
- Updated BR for later fedora
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 1.26-1
- Specfile autogenerated by cpanspec 1.78.
