Name:           perl-Swagger2
Version:        0.66
Release:        1%{?dist}
Summary:        Swagger RESTful API Documentation
License:        Artistic 2.0
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Swagger2/
Source0:        http://www.cpan.org/authors/id/J/JH/JHTHORSEN/Swagger2-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(JSON::Validator) >= 0.63
BuildRequires:  perl(Mojolicious) >= 6.00
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Warnings) >= 0.016
Requires:       perl(JSON::Validator) >= 0.63
Requires:       perl(Mojolicious) >= 6.00
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Swagger2 is a module for generating, parsing and transforming swagger API
specification. It has support for reading swagger specification in JSON
notation and as well YAML format.

%prep
%setup -q -n Swagger2-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes cpanfile META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Jan 05 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.66-1
- Specfile autogenerated by cpanspec 1.78.
