Name:           perl-ConfigReader-Simple
Version:        1.29
Release:        1%{?dist}
Summary:        Simple line-oriented configuration file parser
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/ConfigReader-Simple/
Source0:        http://www.cpan.org/authors/id/B/BD/BDFOY/ConfigReader-Simple-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Output)
BuildRequires:  perl(Test::Warn)
Requires:       perl(Test::Output)
Requires:       perl(Test::Warn)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
ConfigReader::Simple reads and parses simple configuration files. It is
designed to be smaller and simpler than the ConfigReader module and is more
suited to simple configuration files.

%prep
%setup -q -n ConfigReader-Simple-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Sep 29 2015 Nicholas van Oudtshoorn <vanoudt@gmail.com> 1.29-1
- Specfile autogenerated by cpanspec 1.78.
