Name:           perl-Template-Plugin-Stash
Version:        1.006
Release:        1%{?dist}
Summary:        Expose the stash, ideal for Dumpering
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Template-Plugin-Stash/
Source0:        http://www.cpan.org/authors/id/P/PO/PODMASTER/Template-Plugin-Stash-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Template::Plugin)
BuildRequires:  perl(Test::Simple) >= 0.44
Requires:       perl(Template::Plugin)
Requires:       perl(Test::Simple) >= 0.44
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Instead of messing with [% PERL %] blocks to get at the stash, simply [%
USE Stash %].

%prep
%setup -q -n Template-Plugin-Stash-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes LICENSE README Todo
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Sep 29 2015 Nicholas van Oudtshoorn <vanoudt@gmail.com> 1.006-1
- Specfile autogenerated by cpanspec 1.78.
