Name:           perl-MooseX-RW
Version:        0.003
Release:        2%{?dist}
Summary:        MooseX::RW Perl module
License:        GPL+
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MooseX-RW/
Source0:        http://www.cpan.org/authors/id/F/FR/FREDERICD/MooseX-RW-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Carp)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(File::Temp)
BuildRequires:  perl(Moose::Role)
BuildRequires:  perl(strict)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(warnings)
Requires:       perl(Carp)
Requires:       perl(Moose::Role)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))
Provides:	perl(MooseX::RW::Reader)
Provides:       perl(MooseX::RW::Reader::File)
Provides:       perl(MooseX::RW::Writer)

%description
SYNOPSIS    Let suppose you have a voice box on you phone. You want to
display all    number of your messages.

%prep
%setup -q -n MooseX-RW-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes dist.ini LICENSE README weaver.ini
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Dec 13 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.003-2
- Manual Provides
* Thu May 26 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.003-1
- Specfile autogenerated by cpanspec 1.78.
