Name:           perl-Lingua-Ispell
Version:        0.07
Release:        1%{?dist}
Summary:        Lingua::Ispell Perl module
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Lingua-Ispell/
Source0:        http://www.cpan.org/authors/id/J/JD/JDPORTER/Lingua-Ispell-%{version}.tar.gz
Patch0:         ispell-fix-location.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
Requires:       aspell,aspell-en
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Lingua::Ispell::spellcheck() takes one argument. It must be a string, and
it should contain only printable characters. One allowable exception is a
terminal newline, which will be chomped off anyway. The line is fed to a
coprocess running ispell for analysis. ispell parses the line into "terms"
according to the language-specific rules in effect.

%prep
%setup -q -n Lingua-Ispell-%{version}
%patch0 -p1

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor SITEPREFIX=/usr 
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README spellcheck
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Sep 29 2015 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.07-1
- Specfile autogenerated by cpanspec 1.78.
