Name:           perl-Moo
Version:        2.003000
Release:        1%{?dist}
Summary:        Minimalist Object Orientation (with Moose compatibility)
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Moo/
Source0:        http://www.cpan.org/authors/id/H/HA/HAARG/Moo-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl >= 0:5.006
BuildRequires:  perl(Class::Method::Modifiers) >= 1.1
BuildRequires:  perl(Class::XSAccessor) >= 1.18
BuildRequires:  perl(Devel::GlobalDestruction) >= 0.11
BuildRequires:  perl(Exporter) >= 5.57
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Module::Runtime) >= 0.014
BuildRequires:  perl(Role::Tiny) >= 2.000004
BuildRequires:  perl(Scalar::Util)
BuildRequires:  perl(strictures) >= 2
BuildRequires:  perl(Sub::Defer) >= 2.003001
BuildRequires:  perl(Sub::Name) >= 0.08
BuildRequires:  perl(Sub::Quote) >= 2.003001
BuildRequires:  perl(Test::Fatal) >= 0.003
BuildRequires:  perl(Test::More) >= 0.94
Requires:       perl(Class::Method::Modifiers) >= 1.1
Requires:       perl(Class::XSAccessor) >= 1.18
Requires:       perl(Devel::GlobalDestruction) >= 0.11
Requires:       perl(Exporter) >= 5.57
Requires:       perl(Module::Runtime) >= 0.014
Requires:       perl(Role::Tiny) >= 2.000004
Requires:       perl(Scalar::Util)
Requires:       perl(strictures) >= 2
Requires:       perl(Sub::Defer) >= 2.003001
Requires:       perl(Sub::Name) >= 0.08
Requires:       perl(Sub::Quote) >= 2.003001
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
Moo is an extremely light-weight Object Orientation system. It allows one
to concisely define objects and roles with a convenient syntax that avoids
the details of Perl's object system. Moo contains a subset of Moose and is
optimised for rapid startup.

%prep
%setup -q -n Moo-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Dec 13 2016 Nicholas van Oudtshoorn 2.003000-1
- Specfile autogenerated by cpanspec 1.78.
