Name:           perl-JSON-Validator
Version:        0.90
Release:        1%{?dist}
Summary:        Validate data against a JSON schema
License:        Artistic 2.0
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/JSON-Validator/
Source0:        http://www.cpan.org/authors/id/J/JH/JHTHORSEN/JSON-Validator-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Mojolicious) >= 6.00
BuildRequires:  perl(Test::More) >= 0.88
BuildRequires:  perl(Test::Warnings) >= 0.016
BuildRequires:  perl(Test::Mojo)
Requires:       perl(Mojolicious) >= 6.00
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
JSON::Validator is a class for validating data against JSON schemas. You
might want to use this instead of JSON::Schema if you need to validate data
against draft 4 of the specification.

%prep
%setup -q -n JSON-Validator-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes cpanfile META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Tue Dec 13 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.90-1
- New upstream release 
* Tue Jan 05 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.64-1
- Specfile autogenerated by cpanspec 1.78.
