Name:           perl-Text-CSV-Encoded
Version:        0.22
Release:        1%{?dist}
Summary:        Encoding aware Text::CSV
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/Text-CSV-Encoded/
Source0:        http://www.cpan.org/authors/id/M/MA/MAKAMAKA/Text-CSV-Encoded-%{version}.tar.gz
Patch0:         widechar-fixes.patch
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::Harness)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Text::CSV) >= 1.31
Requires:       perl(Test::Harness)
Requires:       perl(Test::More)
Requires:       perl(Text::CSV) >= 1.31
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This module inherits Text::CSV and is aware of input/output encodings.

%prep
%setup -q -n Text-CSV-Encoded-%{version}
%patch0 -p1
%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes META.json README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 0.22-1
- Specfile autogenerated by cpanspec 1.78.
