Name:           perl-PDF-Reuse-Barcode
Version:        0.07
Release:        1%{?dist}
Summary:        Create barcodes for PDF documents with PDF::Reuse
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/PDF-Reuse-Barcode/
Source0:        http://www.cpan.org/authors/id/C/CN/CNIGHS/PDF-Reuse-Barcode-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(Barcode::Code128)
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(GD::Barcode)
BuildRequires:  perl(GD::Barcode::Code39)
BuildRequires:  perl(GD::Barcode::COOP2of5)
BuildRequires:  perl(GD::Barcode::EAN13)
BuildRequires:  perl(GD::Barcode::EAN8)
BuildRequires:  perl(GD::Barcode::IATA2of5)
BuildRequires:  perl(GD::Barcode::Industrial2of5)
BuildRequires:  perl(GD::Barcode::ITF)
BuildRequires:  perl(GD::Barcode::Matrix2of5)
BuildRequires:  perl(GD::Barcode::NW7)
BuildRequires:  perl(GD::Barcode::UPCA)
BuildRequires:  perl(GD::Barcode::UPCE)
BuildRequires:  perl(PDF::Reuse)
Requires:       perl(Barcode::Code128)
Requires:       perl(GD::Barcode)
Requires:       perl(GD::Barcode::Code39)
Requires:       perl(GD::Barcode::COOP2of5)
Requires:       perl(GD::Barcode::EAN13)
Requires:       perl(GD::Barcode::EAN8)
Requires:       perl(GD::Barcode::IATA2of5)
Requires:       perl(GD::Barcode::Industrial2of5)
Requires:       perl(GD::Barcode::ITF)
Requires:       perl(GD::Barcode::Matrix2of5)
Requires:       perl(GD::Barcode::NW7)
Requires:       perl(GD::Barcode::UPCA)
Requires:       perl(GD::Barcode::UPCE)
Requires:       perl(PDF::Reuse)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This is a sub-module to PDF::Reuse. It creates barcode "images" to be used
in PDF documents. It uses GD::Barcode and its sub-modules:
GD::Barcode::Code39, COOP2of5, EAN13 and so on, to calculate the barcode
pattern. For Code128 it uses Barcode::Code128.

%prep
%setup -q -n PDF-Reuse-Barcode-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 0.07-1
- Specfile autogenerated by cpanspec 1.78.
