Name:           perl-MARC-File-MARCMaker
Version:        0.05
Release:        1%{?dist}
Summary:        Work with MARCMaker/MARCBreaker records
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/MARC-File-MARCMaker/
Source0:        http://www.cpan.org/authors/id/E/EI/EIJABB/MARC-File-MARCMaker-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(MARC::Record)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
The MARC-File-MARCMaker distribution is an extension to the MARC-Record
distribution for working with MARC21 data using the format used by the
Library of Congress MARCMaker and MARCBreaker programs.

%prep
%setup -q -n MARC-File-MARCMaker-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes README
%{perl_vendorlib}/*
%{_bindir}/*
%{_mandir}/man3/*
%{_mandir}/man1/*

%changelog
* Thu Jun 30 2016 Nicholas van Oudtshoorn <vanoudt@gmail.com> 0.05-1
- Specfile autogenerated by cpanspec 1.78.
