---
abstract: 'Catmandu modules for working with MARC data'
author:
  - 'Patrick Hochstenbach, C<< <patrick.hochstenbach at ugent.be> >>'
build_requires:
  Module::Build: '0.28'
  Pod::Simple::HTML: '3.23'
  Test::Deep: '0'
  Test::More: '1.001003'
  Test::Pod: '0'
  Test::Simple: '1.001003'
  Test::Warnings: '0'
  XML::XPath: '1.13'
configure_requires:
  Module::Build: '0.28'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.039, Dist::Milla version v1.0.15, CPAN::Meta::Converter version 2.150005'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Catmandu-MARC
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Carp: '0'
  Catmandu: '1.0201'
  JSON::XS: '2.3'
  List::Util: '0'
  MARC::File::MARCMaker: '0.05'
  MARC::File::MiJ: '0.04'
  MARC::File::XML: v1.0.3
  MARC::Lint: '0'
  MARC::Parser::RAW: '0'
  MARC::Record: v2.0.6
  Memoize: '0'
  Moo: '1.0'
  MooX::Singleton: '0'
  YAML::XS: '0.34'
  perl: v5.10.1
resources:
  bugtracker: https://github.com/LibreCat/Catmandu-MARC/issues
  homepage: https://github.com/LibreCat/Catmandu-MARC
  repository: https://github.com/LibreCat/Catmandu-MARC.git
version: '1.03'
x_contributors:
  - 'Chris Cormack <chrisc@catalyst.net.nz>'
  - 'Jakob Voss <voss@gbv.de>'
  - 'Johann Rolschewski <jorol@cpan.org>'
  - 'Johann Rolschewski <rolschewski@gmail.com>'
  - 'Nicolas Steenlant <nicolas.steenlant@ugent.be>'
  - 'Patrick Hochstenbach <Patrick.Hochstenbach@UGent.be>'
  - 'Patrick Hochstenbach <patrick.hochstenbach@ugent.be>'
  - 'Robin Sheat <robin@catalyst.net.nz>'
