Name:           perl-CGI-Session-Serialize-yaml
Version:        4.26
Release:        1%{?dist}
Summary:        Serializer for CGI::Session
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/CGI-Session-Serialize-yaml/
Source0:        http://www.cpan.org/authors/id/R/RS/RSAVAGE/CGI-Session-Serialize-yaml-%{version}.tgz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(CGI::Session) >= 4.3
BuildRequires:  perl(CGI::Session::ErrorHandler) >= 4.3
BuildRequires:  perl(File::Spec)
BuildRequires:  perl(Module::Build)
BuildRequires:  perl(Test::More)
BuildRequires:  perl(Test::Pod)
Requires:       perl(CGI::Session) >= 4.3
Requires:       perl(CGI::Session::ErrorHandler) >= 4.3
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This library can be used by CGI::Session to serialize session data. It uses
YAML, or the faster C implementation, YAML::Syck if it is available. YAML
serializers exist not just for Perl but also other dynamic languages, such
as PHP, Python, and Ruby, so storing session data in this format makes it
easy to share session data across different languages.

%prep
%setup -q -n CGI-Session-Serialize-yaml-%{version}

%build
%{__perl} Build.PL installdirs=vendor
./Build

%install
rm -rf $RPM_BUILD_ROOT

./Build install destdir=$RPM_BUILD_ROOT create_packlist=0
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
./Build test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changelog.ini CHANGES README
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 4.26-1
- Specfile autogenerated by cpanspec 1.78.
