Name:           perl-PDF-Table
Version:        0.9.9
Release:        1%{?dist}
Summary:        Utility class for building table layouts in a PDF::API2 object
License:        GPL+ or Artistic
Group:          Development/Libraries
URL:            http://search.cpan.org/dist/PDF-Table/
Source0:        http://www.cpan.org/authors/id/O/OM/OMEGA/PDF-Table-%{version}.tar.gz
BuildRoot:      %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch:      noarch
BuildRequires:  perl(ExtUtils::MakeMaker)
BuildRequires:  perl(Test::More)
Requires:       perl(:MODULE_COMPAT_%(eval "`%{__perl} -V:version`"; echo $version))

%description
This class is a utility for use with the PDF::API2 module from CPAN. It can
be used to display text data in a table layout within a PDF. The text data
must be in a 2D array (such as returned by a DBI statement handle
fetchall_arrayref() call). The PDF::Table will automatically add as many
new pages as necessary to display all of the data. Various layout
properties, such as font, font size, and cell padding and background color
can be specified for each column and/or for even/odd rows. Also a
(non)repeated header row with different layout properties can be specified.

%prep
%setup -q -n PDF-Table-%{version}

%build
%{__perl} Makefile.PL INSTALLDIRS=vendor
make %{?_smp_mflags}

%install
rm -rf $RPM_BUILD_ROOT

make pure_install PERL_INSTALL_ROOT=$RPM_BUILD_ROOT

find $RPM_BUILD_ROOT -type f -name .packlist -exec rm -f {} \;
find $RPM_BUILD_ROOT -depth -type d -exec rmdir {} 2>/dev/null \;

%{_fixperms} $RPM_BUILD_ROOT/*

%check
make test

%clean
rm -rf $RPM_BUILD_ROOT

%files
%defattr(-,root,root,-)
%doc Changes Makefile META.json MYMETA.json MYMETA.yml README README.md
%{perl_vendorlib}/*
%{_mandir}/man3/*

%changelog
* Thu Aug 13 2015 Nicholas van Oudtshoorn - <vanoudt@gmail.com> 0.9.9-1
- Specfile autogenerated by cpanspec 1.78.
